{"name": "test_no_such_login", "status": "passed", "description": "Проверка невозможности залогиниться с несуществующим аккаунтом. Получаем ошибку 404", "steps": [{"name": "Логин курьера", "status": "passed", "parameters": [{"name": "payload", "value": "{'login': 'pyfetnhfwf', 'password': 'txafxlkjav', 'firstName': 'sxeazfokjn'}"}], "start": 1717775537970, "stop": 1717775538023}], "start": 1717775537970, "stop": 1717775538023, "uuid": "6cdf3a3f-41c6-48f2-887d-7ad893eebdff", "historyId": "f8ba477e2ecf698f789d7f765c2b2fc5", "testCaseId": "f8ba477e2ecf698f789d7f765c2b2fc5", "fullName": "tests.test_login_courier.TestLoginCourier#test_no_such_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "NB-MP25VCCB"}, {"name": "thread", "value": "12600-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}