{"name": "test_get_order_of_his_number_with__non_existent_error", "status": "passed", "description": "Проверка невозможности получить заказ, если отправить несуществующий номер. Получаем код 404 и сообщение: Заказ не найден", "steps": [{"name": "Получить заказ по его номеру", "status": "passed", "parameters": [{"name": "track_number", "value": "'0'"}], "start": 1718006394164, "stop": 1718006394246}], "start": 1718006394164, "stop": 1718006394246, "uuid": "85bd9552-0ffc-4b91-aab4-8613bcd69828", "historyId": "46c097b163a33b4760b55f8dbadd14fa", "testCaseId": "46c097b163a33b4760b55f8dbadd14fa", "fullName": "tests.test_get_order_of_his_number.TestGetOrder#test_get_order_of_his_number_with__non_existent_error", "labels": [{"name": "feature", "value": "Ручка /api/v1/orders/track"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order_of_his_number"}, {"name": "subSuite", "value": "TestGetOrder"}, {"name": "host", "value": "NB-MP25VCCB"}, {"name": "thread", "value": "18164-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order_of_his_number"}]}