{"name": "test_get_order_of_his_number_with__non_existent_error", "status": "passed", "description": "Проверка невозможности получить заказ, если отправить несуществующий номер. Получаем код 404 и сообщение: Заказ не найден", "steps": [{"name": "Получить заказ по его номеру", "status": "passed", "parameters": [{"name": "track_number", "value": "'0'"}], "start": 1717775537183, "stop": 1717775537275}], "start": 1717775537183, "stop": 1717775537275, "uuid": "4258530d-b972-4fc6-be34-a0aeac17bf2a", "historyId": "46c097b163a33b4760b55f8dbadd14fa", "testCaseId": "46c097b163a33b4760b55f8dbadd14fa", "fullName": "tests.test_get_order_of_his_number.TestGetOrder#test_get_order_of_his_number_with__non_existent_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order_of_his_number"}, {"name": "subSuite", "value": "TestGetOrder"}, {"name": "host", "value": "NB-MP25VCCB"}, {"name": "thread", "value": "12600-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order_of_his_number"}]}